# Generated by Django 6.0.5 on 2026-06-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_add_guest_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='unit_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Per Hour'), ('daily', 'Per Day'), ('monthly', 'Per Month')], default='fixed', max_length=10),
        ),
    ]
