# Generated by Django 6.0.5 on 2026-06-12 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_lineitem_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('NPR', 'NPR-Nepali Rupee'), ('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('PKR', 'PKR - Pakistani Rupee'), ('INR', 'INR - Indian Rupee')], default='USD', max_length=3),
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('paypal', 'PayPal'), ('bank', 'Bank Transfer')], default='paypal', max_length=10)),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_holder', models.CharField(blank=True, max_length=90)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='invoices.invoice')),
            ],
        ),
    ]
