# Generated by Django 6.0.5 on 2026-06-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_currency_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
